name: Moudy Photo
pygments: true

raw_image_path: _photos
processed_image_path: photos

asset_pipeline:
  gzip: true

images:
  raw_path: _photos
  processed_path: photos
  file_name_seperator: _
  sizes:
    medium: 1200x1200
    thumbnail: 300x300

# hash passed into gallery.html
view:
  site:
    title: Moudy
